import type {Analysis,PR,PRSummary,Repository,Simulation,UploadInspection,UserAnalysis} from "./types";
// Production and preview use Vercel Services on one origin. The override exists only
// for local Next.js development, where FastAPI runs separately on port 8000.
const BASE=process.env.NODE_ENV==="development"?(process.env.NEXT_PUBLIC_ENGINE_URL??"http://localhost:8000").replace(/\/$/,""):"";
type ErrorPayload={error?:{code?:string;message?:string;request_id?:string};detail?:string};
function fallbackMessage(status:number){if(status===404)return "The deployment API route was not found. Verify the IMerge deployment and try again.";if(status===408||status===504)return "The analysis timed out. Try again with a smaller change or use the guided example.";if(status===429)return "GitHub rate limit reached. Try again shortly or use the guided example.";if(status===502)return "GitHub is temporarily unavailable or returned an unreadable response.";if(status===503)return "The analysis service is temporarily unavailable.";if(status>=500)return "The analysis service failed while processing this change.";return `The analysis request was rejected (${status}).`}
function responseError(status:number,payload:ErrorPayload,requestId:string|null){const message=payload.error?.message??payload.detail??fallbackMessage(status);const id=payload.error?.request_id??requestId;return new Error(id?`${message} Reference: ${id}`:message)}
async function readResponse<T>(response:Response):Promise<T>{const text=await response.text();let payload:unknown;try{payload=JSON.parse(text) as unknown}catch{if(!response.ok)throw responseError(response.status,{},response.headers.get("x-request-id"));throw new Error("The analysis service returned an unreadable response. Try again shortly.")}if(!response.ok)throw responseError(response.status,payload as ErrorPayload,response.headers.get("x-request-id"));return payload as T}
async function fetchEngine(path:string,init?:RequestInit){try{return await fetch(`${BASE}${path}`,{...init,cache:"no-store"})}catch{throw new Error("The IMerge analysis service could not be reached. Check your connection and retry; if this continues, the deployment API routing may be unavailable.")}}
async function request<T>(path:string,init?:RequestInit):Promise<T>{return readResponse<T>(await fetchEngine(path,init))}
export const api={repositories:()=>request<Repository[]>("/api/v1/repositories"),prs:(id:string)=>request<PRSummary[]>(`/api/v1/repositories/${id}/pull-requests`),pr:(id:string)=>request<PR>(`/api/v1/pull-requests/${id}`),analyze:(id:string)=>request<Analysis>(`/api/v1/pull-requests/${id}/analyze`,{method:"POST"}),simulate:(id:string)=>request<Simulation>(`/api/v1/pull-requests/${id}/simulate`,{method:"POST"})};
export async function uploadRequest<T>(path:string,body:FormData|{url:string},onProgress?:(value:number)=>void):Promise<T>{if(body instanceof FormData)return new Promise<T>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",`${BASE}${path}`);xhr.upload.onprogress=event=>{if(event.lengthComputable)onProgress?.(Math.max(4,Math.round(event.loaded/event.total*72)))};xhr.onload=()=>{let payload:unknown;try{payload=JSON.parse(xhr.responseText) as unknown}catch{reject(xhr.status?responseError(xhr.status,{},xhr.getResponseHeader("x-request-id")):new Error("The analysis service returned an unreadable response. Try again shortly."));return}if(xhr.status<200||xhr.status>=300){reject(responseError(xhr.status,payload as ErrorPayload,xhr.getResponseHeader("x-request-id")));return}onProgress?.(100);resolve(payload as T)};xhr.onerror=()=>reject(new Error("The IMerge analysis service could not be reached. Check your connection and retry; if this continues, the deployment API routing may be unavailable."));xhr.ontimeout=()=>reject(new Error("The analysis timed out. Try again with a smaller change or use the guided example."));xhr.timeout=55_000;onProgress?.(2);xhr.send(body)});onProgress?.(18);const response=await fetchEngine(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});onProgress?.(82);const payload=await readResponse<T>(response);onProgress?.(100);return payload}
export const intakeApi={inspectGithub:(url:string,p?:(n:number)=>void)=>uploadRequest<UploadInspection>("/api/v1/github/inspect",{url},p),analyzeGithub:(url:string,p?:(n:number)=>void)=>uploadRequest<UserAnalysis>("/api/v1/github/analyze",{url},p),inspectBundle:(file:File,p?:(n:number)=>void)=>{const form=new FormData();form.append("bundle",file);return uploadRequest<UploadInspection>("/api/v1/git-bundles/inspect",form,p)},analyzeBundle:(file:File,base:string,head:string,p?:(n:number)=>void)=>{const form=new FormData();form.append("bundle",file);form.append("base",base);form.append("head",head);return uploadRequest<UserAnalysis>("/api/v1/git-bundles/analyze",form,p)},inspectProject:(archive:File,diff:File,p?:(n:number)=>void)=>{const form=new FormData();form.append("archive",archive);form.append("diff",diff);return uploadRequest<UploadInspection>("/api/v1/uploads/inspect",form,p)},analyzeProject:(archive:File,diff:File,p?:(n:number)=>void)=>{const form=new FormData();form.append("archive",archive);form.append("diff",diff);return uploadRequest<UserAnalysis>("/api/v1/uploads/analyze",form,p)}};
